### PR TITLE
WRR-1519: Update dependencies' patch version

### PR DESCRIPTION
**Pull request by hong6316**
### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Update dependencies' patch version

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Update dependencies' patch version

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRR-1519

### Comments
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

### CODE REVIEW

**Review by seunghoh — CHANGES_REQUESTED** [review]
You changed patch version. Not minor. 
and Do we change the patch version in the package.json even we are using `^`?

**Review by daniel-stoian-lgp — APPROVED** [review]
LGTM

**Comment by daniel-stoian-lgp** [comment]
> You changed patch version. Not minor. and Do we change the patch version in the package.json even we are using `^`?

@seunghoh , if it looks ok, for you, can you change your approval status?

**Comment by hong6316** [comment]
> You changed patch version. Not minor. and Do we change the patch version in the package.json even we are using `^`?

The above question was answered verbally.
I also left a note in the PR description that the patch version was modified.

**Review by seunghoh — APPROVED** [review]

**Pull request merged**
